// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPtQfkzlitBIgrgPt-Z4Vfpm5tRTegxV4',
    appId: '1:243535056458:web:9fe7a04c1287010e3520b3',
    messagingSenderId: '243535056458',
    projectId: 'money-tracker-7ea28',
    authDomain: 'money-tracker-7ea28.firebaseapp.com',
    storageBucket: 'money-tracker-7ea28.firebasestorage.app',
    measurementId: 'G-0733420K3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1QwEs2hsm_13u-_z0AbqKY1H7aKfcIVo',
    appId: '1:243535056458:android:41caeab7711ceb2e3520b3',
    messagingSenderId: '243535056458',
    projectId: 'money-tracker-7ea28',
    storageBucket: 'money-tracker-7ea28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnCWyv5slbsV_zwtopQlXFAKApjwBWmsA',
    appId: '1:243535056458:ios:a15491991d4594163520b3',
    messagingSenderId: '243535056458',
    projectId: 'money-tracker-7ea28',
    storageBucket: 'money-tracker-7ea28.firebasestorage.app',
    iosBundleId: 'com.example.mbapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnCWyv5slbsV_zwtopQlXFAKApjwBWmsA',
    appId: '1:243535056458:ios:a15491991d4594163520b3',
    messagingSenderId: '243535056458',
    projectId: 'money-tracker-7ea28',
    storageBucket: 'money-tracker-7ea28.firebasestorage.app',
    iosBundleId: 'com.example.mbapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPtQfkzlitBIgrgPt-Z4Vfpm5tRTegxV4',
    appId: '1:243535056458:web:2531152dd74a4ea43520b3',
    messagingSenderId: '243535056458',
    projectId: 'money-tracker-7ea28',
    authDomain: 'money-tracker-7ea28.firebaseapp.com',
    storageBucket: 'money-tracker-7ea28.firebasestorage.app',
    measurementId: 'G-DMLPKV6QMN',
  );
}
